snhuproduct/turbine

apps/toboggan-app/src/app/user/components/user-table/data/user-table-header.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
yarn.lock

Refactored sorting logic for the user table and got status filters working

Snhut 1520 user table refactoring and fixes

---

apps/toboggan-api/src/controllers/groups/groups.controller.ts
apps/toboggan-api/src/providers/groups/groups.service.ts
apps/toboggan-api/src/providers/users/users.service.ts
apps/toboggan-app/src/app/shared/services/user/user.service.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.types.ts
libs/toboggan-common/src/lib/toboggan-common.ts
yarn.lock

Description
===
This PR covers this [Jira Ticket](https://collectiveshift.atlassian.net/jira/software/c/projects/SNHUT/boards/132?modal=detail&selectedIssue=SNHUT-584&assignee=62901d109c617b006a6eec1c) and basically aims to implement an user activation/deactivation process.
Demo
===
https://user-images.githubusercontent.com/107008166/184690624-3f831cad-2f3a-481f-8a9e-424d89375c33.mp4

Snhut 584 user deactivate user account

---

apps/toboggan-app/src/app/shared/components/banner/banner.component.html
apps/toboggan-app/src/app/shared/services/banner/banner.service.ts
apps/toboggan-app/src/app/shared/services/banner/banner.types.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts

Description
========
This PR implements the notification banner message whenever a user is activated/deactivated, as required by [this ticket](https://collectiveshift.atlassian.net/jira/software/c/projects/SNHUT/boards/132?modal=detail&selectedIssue=SNHUT-592&assignee=62901d109c617b006a6eec1c)
Demo
====
https://drive.google.com/file/d/1mx3ebG6Q89Oj4llw8AukfY_kV7j5fgf4/view

SNHUT-592: Deactivation success/error states

---

apps/toboggan-app/src/app/shared/services/table-sorting/table-sorting.mock.ts
apps/toboggan-app/src/app/shared/services/table-sorting/table-sorting.service.spec.ts
apps/toboggan-app/src/app/shared/services/table-sorting/table-sorting.service.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts

This PR extracts some sorting logic from the user table and places it in a dedicated TableSortingService, to respect the Single Responsability Principle
This should be applied for both users and groups!

SNHUT-1590: Refactor of table sorting logic

---

apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts

Restructured group list code, using @joao-sd service for sorting

Restructered group list table implementation

---

apps/toboggan-app/src/app/user/components/user-table/user-table.component.html
apps/toboggan-app/src/app/user/pages/user-main-page/user-main-page.component.html
package-lock.json
package.json
yarn.lock

Description
=====
This PR implements our latest toboggan-UI changes, adjusting the placement of our Add new user button.

SNHUT-1510-table-cta-slot [WS]

---

apps/toboggan-app/src/app/shared/services/table-data/table-data.service.spec.ts
apps/toboggan-app/src/app/shared/services/table-data/table-data.service.ts
apps/toboggan-app/src/app/shared/services/table-sorting/table-sorting.service.ts
apps/toboggan-app/src/app/user/components/user-table/data/user-table-header.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.html
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
package-lock.json
yarn.lock

- Completes [SNHUT-1575](https://collectiveshift.atlassian.net/browse/SNHUT-1575) : User Management/Search User List Pt. 2
- Completes [SNHUT-1563](https://collectiveshift.atlassian.net/browse/SNHUT-1563) : Pagination fixes
- Completes [SNHUT-1613](https://collectiveshift.atlassian.net/browse/SNHUT-1613) : User table refactoring, introduction to table-data service
- Partially completes [SNHUT-1562](https://collectiveshift.atlassian.net/browse/SNHUT-1562)
- Titles only have the first letter of the first word capitalized
- Search default text is : ~Placeholder~ Search
https://user-images.githubusercontent.com/107949139/185936596-4ede6807-f944-4ebc-8d6f-a1e6fa172c48.mp4

User Management Search User List [Snhut 1236]

---

apps/toboggan-app/src/app/group/components/group-list/group-list.component.html
apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
apps/toboggan-app/src/app/group/components/group-list/group-table.type.ts
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.html
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.spec.ts

This PR addresses following items
1. Added filter feature into group list table
2. Positioned "create user group" button near to table search box

Snhut 1242 group list frontend enhancements

---

apps/toboggan-app/src/app/user/components/user-table/user-table.component.spec.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts

Handle "Reset Password" menu action and show confirmation modal.

Confirmation modal for reset password

---

apps/toboggan-app/src/app/user/components/user-table/data/user-table-header.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.html
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.types.ts
package-lock.json
package.json
yarn.lock

- Completes [SNHUT-1562](https://collectiveshift.atlassian.net/browse/SNHUT-1562) : request-4 
- [Related PR in toboggan-ui-components](https://github.com/snhuproduct/toboggan-ui-components/pull/208)
- Unsubscribe from users API stream if there is an existing subscription
- Pagination will show _Users_ instead of _Items_ , making use of [Ajith's PR](https://github.com/snhuproduct/toboggan-ui-components/pull/207)

SNHUT-1562 - Remove Sorting from Status column

---

apps/toboggan-app/src/app/user/components/user-table/user-table.component.spec.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts

Activate/Deactivate User add missing pieces per the story AC's and refactor.

Activate/Deactivate User Flow

---

apps/toboggan-app-e2e/src/fixtures/users.json
apps/toboggan-app-e2e/src/integration/users.spec.ts
apps/toboggan-app-e2e/src/support/app.po.ts

User Management | User list - Frontend (QA) - https://collectiveshift.atlassian.net/browse/SNHUT-1583

SNHUT-1583 - User Management | User list - Frontend (QA) | E2E test coverage

---

apps/toboggan-app-e2e/src/integration/users.spec.ts

Group Management | Add users to groups via create group modal - Frontend 
https://collectiveshift.atlassian.net/browse/SNHUT-1244

SNHUT-1589- User Management | Deactivation success and error states - Frontend (QA)

---

apps/toboggan-api/src/controllers/groups/groups.controller.ts
apps/toboggan-api/src/providers/groups/groups.service.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.html
apps/toboggan-app/src/app/group/components/group-list/group-list.component.spec.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
apps/toboggan-app/src/app/group/components/group-list/group-table.type.ts
apps/toboggan-app/src/app/group/group.module.ts
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.html
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.spec.ts
apps/toboggan-app/src/app/group/services/group.service.spec.ts
apps/toboggan-app/src/app/group/services/group.service.ts
apps/toboggan-app/src/app/shared/components/banner/banner.component.html
apps/toboggan-app/src/app/shared/pipes/safe-html.pipe.ts
apps/toboggan-app/src/app/shared/shared.module.ts
apps/toboggan-app/src/styles.scss

Following ticket has been handled in this PR
https://collectiveshift.atlassian.net/browse/SNHUT-1247
short video on PR
[delete-group.webm](https://user-images.githubusercontent.com/109214920/186385368-ebb295f0-f263-4d96-a7a1-011cee4d19d7.webm)

Snhut 1247 delete group

---

apps/toboggan-api/src/providers/groups/groups.service.ts
apps/toboggan-app/src/app/group/components/add-users/add-users.component.html
apps/toboggan-app/src/app/group/components/add-users/add-users.component.spec.ts
apps/toboggan-app/src/app/group/components/add-users/add-users.component.ts
apps/toboggan-app/src/app/group/components/create-group/create-group.component.html
apps/toboggan-app/src/app/group/components/create-group/create-group.component.spec.ts
apps/toboggan-app/src/app/group/components/create-group/create-group.component.ts
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.html
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.spec.ts
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.ts
apps/toboggan-app/src/app/shared/components/modal/modal.component.ts

refactored modal trigger buttons and modal instances in group modules using new modal component from @david-mart 's implementation
this is much cleaner
David's implementation 
https://github.com/snhuproduct/toboggan-ws/pull/18
This adds code fixes for following ticket too ( thanks to @maheshwara-sada ) 
https://collectiveshift.atlassian.net/browse/SNHUT-1264

Create group and add user to group modals refactoring using david's modal component

---

apps/toboggan-app-e2e/src/integration/users.spec.ts

User Management | Initiate user password reset - Frontend
https://collectiveshift.atlassian.net/browse/SNHUT-1237

SNHUT-1237 - User Management | Initiate user password reset - Frontend (QA)

---

apps/toboggan-app-e2e/src/integration/users.spec.ts

User Management | User list demo fixes - Frontend
https://collectiveshift.atlassian.net/browse/SNHUT-1562

SNHUT-1562- User Management | User list demo fixes - Frontend (QA)

---

apps/toboggan-app-e2e/src/fixtures/users.json
apps/toboggan-app-e2e/src/integration/users.spec.ts

User Management | Search user list (Part 2)
https://collectiveshift.atlassian.net/browse/SNHUT-1575

SNHUT-1575 - User Management | Search user list (Part 2)

---

apps/toboggan-app-e2e/src/integration/users.spec.ts

User Management | User list pagination fixes - Frontend
https://collectiveshift.atlassian.net/browse/SNHUT-1563

SNHUT-1563 - User Management | User list pagination fixes - Frontend

---

README.md
apps/toboggan-app-e2e/src/integration/group-main-page.spec.ts

SNHUT-587 - Group Management | Create Group - Frontend - https://collectiveshift.atlassian.net/browse/SNHUT-587
Cover the Create User Group modal

SNHUT-1586, SNHUT-587 - Group Management | Create Group - Frontend | E2E test coverage

---

apps/toboggan-app-e2e/src/integration/group-main-page.spec.ts

Group Management | Add users to groups via create group modal - Frontend (QA)
https://collectiveshift.atlassian.net/browse/SNHUT-1587

SNHUT-1587 - Group Management | Add users to groups via create group modal - Frontend (QA)

---

apps/toboggan-app/src/app/group/components/add-users/add-users.component.html
apps/toboggan-app/src/app/shared/services/user/user.service.ts
apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.html
apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
apps/toboggan-app/src/app/user/pages/user-main-page/user-main-page.component.html
apps/toboggan-app/src/app/user/pages/user-main-page/user-main-page.component.spec.ts
apps/toboggan-app/src/app/user/pages/user-main-page/user-main-page.component.ts
yarn.lock

Description
======
This PR aims to hook the edit-user modal to the "edit user" menu action click.
Demo
======
https://user-images.githubusercontent.com/107008166/186963514-4183aa62-99e3-447b-b70b-c39ace1e6d37.mp4

SNHUT-1638: Connecting edit user

---

apps/toboggan-app/src/app/shared/services/user/user.service.ts
apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts

- Addresses the bug filed at [SNHUT-1673](https://collectiveshift.atlassian.net/browse/SNHUT-1673)
https://user-images.githubusercontent.com/107949139/186989713-5b815347-3119-42b4-84a4-33b9ea1917f2.mp4

SNHUT-1673: Editing new user does not update the table

---

apps/toboggan-app-e2e/src/integration/users.spec.ts

User Management | Password reset initiation success or error state - Frontend (Part 1) 
https://collectiveshift.atlassian.net/browse/SNHUT-582

SNHUT-582 - User Management | Password reset initiation success or error state - Frontend (Part 1) (QA)

---

apps/toboggan-app/src/app/group/components/list-users/list-users.component.html
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.html
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.spec.ts
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.ts

Following ticket has been handled in this PR
https://collectiveshift.atlassian.net/browse/SNHUT-588
Please see following screenshots as well

added button for add user in group details page

---

apps/toboggan-app-e2e/src/fixtures/groups.json
apps/toboggan-app-e2e/src/integration/groups.spec.ts
package.json

Group Management | Group list - Frontend - https://collectiveshift.atlassian.net/browse/SNHUT-1242

SNHUT-1242 - Group Management | Group list - Frontend | E2E test coverage

---

apps/toboggan-app-e2e/src/integration/edit-user.spec.ts

User Management | Edit user - Frontend - https://collectiveshift.atlassian.net/browse/SNHUT-583

SNHUT-583 - User Management | Edit user - Frontend | E2E test coverage 

---

apps/toboggan-app-e2e/src/integration/groups.spec.ts

Group Management | Group list - Frontend - https://collectiveshift.atlassian.net/browse/SNHUT-1242
Related PR
https://github.com/snhuproduct/toboggan-ws/pull/31

[Fix] SNHUT-1242 - Group Management (QA)

---

apps/toboggan-app-e2e/src/integration/users.spec.ts

Recreated and updated PR for corresponding target branch
https://github.com/snhuproduct/toboggan-ws/pull/30
User Management | Edit user - Frontend - https://collectiveshift.atlassian.net/browse/SNHUT-583

SNHUT-583 - User Management | Edit user - Frontend (QA)

---

apps/toboggan-app/src/app/group/components/group-list/group-table.type.ts

SNHUT-1714 : Disable Sorting in Group-table's Description Column

---

apps/toboggan-app-e2e/src/fixtures/users.json
apps/toboggan-app-e2e/src/integration/users.spec.ts

User Management | User list pagination fixes - Frontend
https://collectiveshift.atlassian.net/browse/SNHUT-1563
Related PR
https://github.com/snhuproduct/toboggan-ws/pull/44

SNHUT-1563 - User Management | User list pagination fixes - Frontend (QA)

---

apps/toboggan-app-e2e/src/integration/groups.spec.ts

Group Management | Group list - Frontend - https://collectiveshift.atlassian.net/browse/SNHUT-1242
Related PR
https://github.com/snhuproduct/toboggan-ws/pull/31

[Update] SNHUT-1242 - Group Management (QA)

---

apps/toboggan-app-e2e/src/integration/group-main-page.spec.ts

Group Management | Add users to groups via create group modal - Frontend (QA)
https://collectiveshift.atlassian.net/browse/SNHUT-1484

[Update] SNHUT-1484 - Group Management | Add users to groups via create group modal - Frontend (QA)

---

apps/toboggan-api/src/controllers/groups/groups.controller.ts
apps/toboggan-api/src/providers/users/users.service.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.html
apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
apps/toboggan-app/src/app/group/components/list-users/list-users.component.html
apps/toboggan-app/src/app/group/components/list-users/list-users.component.spec.ts
apps/toboggan-app/src/app/group/components/list-users/list-users.component.ts
apps/toboggan-app/src/app/group/components/list-users/types/list-users.type.ts
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.html
apps/toboggan-app/src/app/group/services/group.service.ts
apps/toboggan-app/src/app/shared/components/modal-alert/modal-alert/modal-alert.component.html
apps/toboggan-app/src/app/shared/components/modal-alert/modal-alert/modal-alert.component.spec.ts
apps/toboggan-app/src/app/shared/components/modal-alert/modal-alert/modal-alert.component.ts
apps/toboggan-app/src/app/shared/services/user/user.service.ts
package-lock.json
package.json
yarn.lock

Following ticket has been addressed
https://collectiveshift.atlassian.net/browse/SNHUT-1246

Snhut 1246 remove user from group

---

apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.ts

Following bug has been fixed in this ticket 
https://collectiveshift.atlassian.net/browse/SNHUT-1756

SNHUT-1756

---

apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.html
apps/toboggan-app/src/app/shared/error-message/error-message.directive.spec.ts
apps/toboggan-app/src/app/shared/error-message/error-message.directive.ts
apps/toboggan-app/src/app/shared/shared.module.ts
apps/toboggan-app/src/app/user/components/create-user/create-user.component.html
apps/toboggan-app/src/app/user/components/create-user/create-user.component.spec.ts
apps/toboggan-app/src/app/user/components/create-user/create-user.component.ts
apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.html
apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
apps/toboggan-app/src/app/user/pages/user-main-page/user-main-page.component.html
apps/toboggan-app/src/app/user/pages/user-main-page/user-main-page.component.spec.ts
apps/toboggan-app/src/app/user/pages/user-main-page/user-main-page.component.ts
libs/toboggan-constants/src/lib/toboggan-constants.ts
package-lock.json
package.json
yarn.lock

1. New Users start as active. 
2. Consistency on Capital letters on all screens.
3. Change validation messages.
4. New pattern for validation of names based on discussion with Topher
5. Refactor validation and error messages in a reusable directive, removing related code from the Create and Edit components

Address Demo Feedback. Refactor validation.

---

apps/toboggan-api/src/controllers/groups/groups.controller.spec.ts
apps/toboggan-api/src/controllers/groups/groups.controller.ts
apps/toboggan-api/src/controllers/users/users.controller.spec.ts

Ticket: https://collectiveshift.atlassian.net/browse/SNHUT-1479

API: Unit testing for users and groups

---

.github/pull_request_template.md

- Please write a short description of your changes here. Provide as much context as needed.
- Paste your link here.
| Original | Updated |
| -------- | ------- |
|          |         |
- [JIRA Ticket](https://JIRA_LINK_HERE)

SNHUT-1444: Github PR template

---

.github/workflows/main.yml
package.json
yarn.lock

- This PR implements a Github action job to trigger our unit tests. It will be used as a requirement to merge PRs, from now on. 
- [JIRA Ticket](https://collectiveshift.atlassian.net/jira/software/c/projects/SNHUT/boards/131?modal=detail&selectedIssue=SNHUT-1831&assignee=62901d109c617b006a6eec1c)
- N/A **All new necessary Unit tests were CREATED** to promote code coverage

SNHUT-1831: Implemented unit tests workflow

---

.husky/pre-commit
apps/toboggan-app/src/app/group/components/edit-group/edit-group.component.spec.ts
apps/toboggan-app/src/app/group/components/edit-group/edit-group.component.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
package-lock.json
package.json
yarn.lock

- Group Management | Edit group details success/failure - Frontend
| Original | Updated |
| -------- | ------- |
|          |         |
[https://collectiveshift.atlassian.net/browse/SNHUT-1245](https://collectiveshift.atlassian.net/browse/SNHUT-1245?atlOrigin=eyJpIjoiMzljZjViODAzOWVkNGU4ZDg1MGExMTJiMTM5MGIwMDEiLCJwIjoiaiJ9)

Origin/snhut 1245 -Group Management | Edit group details success/failure - Frontend

---

apps/toboggan-app/src/app/group/components/permission/data/permissions.ts
apps/toboggan-app/src/app/group/components/permission/permission.component.html
apps/toboggan-app/src/app/group/components/permission/permission.component.scss
apps/toboggan-app/src/app/group/components/permission/permission.component.spec.ts
apps/toboggan-app/src/app/group/components/permission/permission.component.ts
apps/toboggan-app/src/app/group/group.module.ts
apps/toboggan-app/src/app/group/pages/group-details-page/data/applicationTab.ts
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.html
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.scss
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.spec.ts
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.ts
apps/toboggan-app/src/app/user/components/create-user/create-user.component.ts
package.json

As an administrator, I want the ability to grant access to applications, So that I can assign application access to users
TODO : 
- Need to add an optional property in the checkbox

Snhut 593 permission mgt

---

apps/toboggan-app/src/app/group/components/edit-group/edit-group.component.html
apps/toboggan-app/src/app/group/components/edit-group/edit-group.component.spec.ts
apps/toboggan-app/src/app/group/components/edit-group/edit-group.component.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.html
apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
apps/toboggan-app/src/app/group/services/group.service.spec.ts
apps/toboggan-app/src/app/group/services/group.service.ts
package-lock.json
package.json
yarn.lock

- Code refactoring for edit group modal
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-1885)

Snhut 1885 refactoring edit group modal

---

apps/toboggan-app/src/app/group/components/list-users/data/user-table-header.ts
apps/toboggan-app/src/app/group/components/list-users/list-users.component.html
apps/toboggan-app/src/app/group/components/list-users/list-users.component.spec.ts
apps/toboggan-app/src/app/group/components/list-users/list-users.component.ts

- Refactoring table logic for group details page
| Original | Updated |
| -------- | ------- |
|          |         |
- [SNHUT-1828](https://collectiveshift.atlassian.net/browse/SNHUT-1828)

SNHUT-1828 :   Refactoring table logic for group details page

---

apps/toboggan-app/src/app/user/components/create-user/create-user.component.html
apps/toboggan-app/src/app/user/components/create-user/create-user.component.scss
package.json

- Tooltip was not working inside create user modal. fixed it 
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-1884)

fixed tooltip issue in create user modal

---

apps/toboggan-app/src/app/group/components/permission/permission.component.html
apps/toboggan-app/src/app/group/components/permission/permission.component.ts

Bug fix on Permission management modal
https://collectiveshift.atlassian.net/browse/SNHUT-2204

Bugfix - button issue should be resolved from ui library

---

apps/toboggan-api/src/app/modules/groups/groups.service.ts

-SNHUT-1364:Group Management | Create Group - Backend
- [SNHUT-1364](https://collectiveshift.atlassian.net/browse/SNHUT-1364)

SNHUT-1364:Group Management | Create Group - Backend

---

apps/toboggan-app/src/app/permission/components/permissions-list/permissions-list.component.ts

- Permission table filter has been updated as per latest discussion with topher and karen
- Discussion is added to jira ticket
- 
[SNHUT-2133.webm](https://user-images.githubusercontent.com/109214920/198518874-ec3f8949-be73-40a2-8a86-2eb010c90d0e.webm)
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2133)

fixed filtering issue in permission list

---

apps/toboggan-app/src/app/app.module.ts
apps/toboggan-app/src/app/login/components/login/login.component.spec.ts
apps/toboggan-app/src/app/shared/auth/activity-monitor.service.ts
apps/toboggan-app/src/app/shared/auth/auth-interceptor.ts
apps/toboggan-app/src/app/shared/auth/auth.guard.ts
apps/toboggan-app/src/app/shared/auth/auth.service.ts
apps/toboggan-app/src/app/shared/shared.module.ts

- Implementation of refresh token functionality in our WS repository (original code by @artem-sada)
- Refactoring of some minor details
- [JIRA Ticket](https://collectiveshift.atlassian.net/jira/software/c/projects/SNHUT/boards/132?modal=detail&selectedIssue=SNHUT-2311&assignee=62901d109c617b006a6eec1c)

SNHUT-2311: Refresh token

---

README.md

- Added URL for `@snhuproduct:registry` API key on 1password

Readme Update with 1password Secret URL

---

apps/toboggan-api/src/app/modules/users/users.service.ts
apps/toboggan-app/src/app/group/components/list-users/list-users.component.ts
apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.html
apps/toboggan-app/src/app/user/components/edit-user/edit-user.component.ts
apps/toboggan-app/src/app/user/components/user-table/mock/usersMock.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.component.ts
apps/toboggan-app/src/app/user/components/user-table/user-table.types.ts
libs/toboggan-common/src/lib/toboggan-common.ts

- Edit user modal was not rendering correct user  -> fixed it
- Review page information was also not correct - fixed it
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2342)

fixed issue in edit modal - rendering correct user

---

apps/toboggan-api/src/controllers/groups/groups.controller.ts
apps/toboggan-api/src/controllers/users/users.controller.ts
apps/toboggan-api/src/dto/groups.dto.ts
apps/toboggan-api/src/dto/users.dto.ts
apps/toboggan-api/src/main.ts
apps/toboggan-api/src/providers/groups/groups.service.ts
apps/toboggan-api/src/providers/users/users.service.ts
libs/toboggan-common/src/lib/toboggan-common.ts
package.json
yarn.lock

- connect ValidationPipe pipe
- add DTO for users
- add DTO for groups
https://user-images.githubusercontent.com/110631003/190729707-888de1ee-5d90-4ef5-942b-8ef02dbe0787.mov
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-1478)

SNHUT-1478: API: Create DTOs for Users and Groups

---

apps/toboggan-api/src/app/modules/groups/groups.controller.spec.ts
apps/toboggan-api/src/app/modules/permissions/permission.controller.spec.ts
apps/toboggan-api/src/app/modules/users/users.controller.spec.ts
apps/toboggan-api/src/app/modules/users/users.controller.ts

Fixing unit tests for group controller and permission controller -SNHUT-2486
| Original | Updated |
| -------- | ------- |
|          |         |
- [SNHUT-2486](https://collectiveshift.atlassian.net/browse/SNHUT-2486)

Fixing unit tests for group controller and permission controller -SNHUT-2486

---

apps/toboggan-app/src/app/assessment/assessment.module.ts
apps/toboggan-app/src/app/assessment/assessment.routing.ts
apps/toboggan-app/src/app/assessment/components/assessment-details/assessment-details.component.html
apps/toboggan-app/src/app/assessment/components/assessment-details/assessment-details.component.scss
apps/toboggan-app/src/app/assessment/components/assessment-details/assessment-details.component.spec.ts
apps/toboggan-app/src/app/assessment/components/assessment-details/assessment-details.component.ts
apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.spec.ts
apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-table.type.ts
apps/toboggan-app/src/app/assessment/pages/assessment-main-page/assessment-main-page.component.html
apps/toboggan-app/src/app/assessment/pages/assessment-main-page/assessment-main-page.component.spec.ts
apps/toboggan-app/src/app/shared/styles/_bootstrap_overrides.scss
apps/toboggan-app/src/app/shared/styles/_colors.scss

Open Submission Details Page from List View  - container
UI Scope:
1. DEV Figma URL - [DEV_SE_NS-MVP_Assessment Management](https://www.figma.com/file/tEAMiDr4ZoGWUzSXmYsTff/DEV_SE_NS-MVP_Assessment-Management?node-id=2262%3A17824)
2. iFrame for the learner submission
3. Toolbar to navigate submissions and academic integrity.
**TODO: 
Replace iframe url with corresponding url
Populate dynamic content submitted by the learner**
- JIRA -[https://collectiveshift.atlassian.net/browse/SNHUT-2640]()

Snhut 2640 assessment details page

---

apps/toboggan-api/src/app/modules/common/utils.ts
apps/toboggan-api/src/app/modules/groups/groups.controller.spec.ts
apps/toboggan-api/src/app/modules/groups/groups.controller.ts
apps/toboggan-api/src/app/modules/groups/groups.dto.ts
apps/toboggan-api/src/app/modules/groups/groups.service.ts
apps/toboggan-api/src/app/modules/permissions/permissions.mock.ts
apps/toboggan-app/src/app/group/components/create-group/create-group.component.ts
apps/toboggan-app/src/app/group/components/edit-group/edit-group.component.spec.ts
apps/toboggan-app/src/app/group/components/edit-group/edit-group.component.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.spec.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
apps/toboggan-app/src/app/group/components/list-users/list-users.component.spec.ts
apps/toboggan-app/src/app/group/components/list-users/list-users.component.ts
apps/toboggan-app/src/app/group/interface/group.type.ts
apps/toboggan-app/src/app/group/pages/group-details-page/group-details-page.component.ts
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.spec.ts
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.ts
apps/toboggan-app/src/app/group/services/group.service.spec.ts
apps/toboggan-app/src/app/group/services/group.service.ts
apps/toboggan-app/src/app/permission/components/permissions-list/permission-test.mock.ts
apps/toboggan-app/src/app/permission/components/permissions-list/permissions-list.component.ts
libs/toboggan-common/src/lib/toboggan-common.ts

- Integrate API for removing user from group. Use existing apis available. Update unit test cases as well
https://user-images.githubusercontent.com/116863369/204482299-39ca4755-e2bb-4055-9f99-e3d866cb2e29.mp4
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2690)

remove user from group api integration

---

apps/toboggan-api/src/app/modules/groups/groups.controller.ts
apps/toboggan-api/src/app/modules/groups/groups.dto.ts
apps/toboggan-api/src/app/modules/groups/groups.service.ts
apps/toboggan-app/src/app/group/components/add-users/add-users.component.spec.ts
apps/toboggan-app/src/app/group/components/add-users/add-users.component.ts
apps/toboggan-app/src/app/group/pages/group-main-page/group-main-page.component.spec.ts
apps/toboggan-app/src/app/group/services/group.service.spec.ts
apps/toboggan-app/src/app/group/services/group.service.ts
libs/toboggan-common/src/lib/toboggan-common.ts

- Api integration for adding users to group while creating a group 
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2704)

Add users to group from create group modal - Api integration

---

apps/toboggan-api/src/app/modules/groups/groups.controller.ts
apps/toboggan-api/src/app/modules/groups/groups.service.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.spec.ts
apps/toboggan-app/src/app/group/components/group-list/group-list.component.ts
apps/toboggan-app/src/app/group/services/group.service.ts

- Delete group API integration
https://user-images.githubusercontent.com/116863369/205031294-9d8d47bb-dc0b-4c5c-b88a-23b704cb5e8c.mp4
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-2736)

Delet group api integration

---

apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.spec.ts
apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-list.component.ts
apps/toboggan-app/src/app/assessment/components/assessment-list/assessment-table.type.ts
apps/toboggan-app/src/app/assessment/services/assessment.service.ts

https://collectiveshift.atlassian.net/browse/SNHUT-1994
- As an assessor,I need the ability to remove a flag from an assessment, So I can continue grading the assessment. 
https://collectiveshift.atlassian.net/browse/SNHUT-1992
- As an assessor,I need the ability to identify which assessments are flagged, So that I can focus on non-flagged assessments
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-1994)
- [JIRA Ticket](https://collectiveshift.atlassian.net/browse/SNHUT-1992)

Snhut 1992 flagged assessment state
